In [1]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
import numpy as np

X=np.array([
    [1,2,3,4],
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44],
    [51,52,53,54],
    [61,62,63,64],
    [71,72,73,74]
])
 
y=np.array([1,1,0,0,1,1,0,0])

kf= KFold(n_splits=4)
print(kf.split(X))


<generator object _BaseKFold.split at 0x000002064D9C31C8>


In [7]:
X=np.array([
    [1,2,3,4],
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44],
    [51,52,53,54],
    [61,62,63,64],
    [71,72,73,74]
])
X[:,1]

array([ 2, 12, 22, 32, 42, 52, 62, 72])

In [12]:

# conding :utf-8  
from sklearn.linear_model import LogisticRegression  
import numpy as np  
x_train = np.array([[1,2,3],  
                    [1,3,4],  
                    [2,1,2],  
                    [4,5,6],  
                    [3,5,3],  
                    [1,7,2]])  
  
y_train = np.array([3, 3, 3, 2, 2, 2])  
  
x_test = np.array([[2,2,2],  
                   [3,2,6],  
                   [1,7,4]])  
  
clf = LogisticRegression()  
clf.fit(x_train, y_train)  
  
# 返回预测标签  
# print(clf.predict(x_test))  
  
# 返回预测属于某标签的概率
print(clf.predict_proba(x_test))
out = clf.predict_proba(x_test)[:, 1]
print(out)
print(out.ravel())



[[0.56651809 0.43348191]
 [0.15598162 0.84401838]
 [0.86852502 0.13147498]]
[0.43348191 0.84401838 0.13147498]
[0.43348191 0.84401838 0.13147498]


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [2]:
print("New")

New
